### ISSUE TITLE
나의 Todo

### ISSUE THREAD

**Issue by olsi10** [2023-mirimi/mirimi-client#3]
- Drawer 탭 수정 (바로가기)
- 홈 페이지
  - 시간표 수정/삽입
  - 급식 API 끌어다가 넣기
- 공모전 페이지
  - 정렬 (최신순, 교내/교외 구별)
  - 디자인/개발 해시태그 생성

![Image](https://github.com/2023-mirimi/mirimi-client/assets/87300199/ed3ebb0c-adf3-4b8c-a6dc-62d240cc4312)

**Comment by jinaoah** [comment]
Home 페이지에서 <VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.> 이러한 에러가 나던데
원인은 **ScrollView와 FlatList 태그를 중첩으로 사용**해서 나는 에러래. 그래서 FlatList말고 [VirtualizedList](https://reactnative.dev/docs/virtualizedlist)이 태그를 쓰는 걸 추천하더라공
